### ISSUE TITLE
Error upon install

### ISSUE THREAD

**Issue by pcav** [Open-EO/openeo-qgis-plugin#38]
```
Impossibile caricare il plugin 'openeo-qgis-plugin-master' a causa di un errore chiamando il metodo classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "/usr/local/src/qgis/QGIS/build-qgis-master/output/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/grib/python/plugins/openeo-qgis-plugin-master/__init__.py", line 36, in classFactory
    return OpenEO(iface)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/grib/python/plugins/openeo-qgis-plugin-master/openeo_connector.py", line 51, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable
```

**Comment by bgoesswe** [comment]
Thanks for the report: 
Can you provide us the QGIS version that you used?

**Comment by bgoesswe** [comment]
Seems related to 
https://github.com/PANOimagen/batch_hillshader/issues/4
