### ISSUE TITLE
Installation from zip fails

### ISSUE THREAD

**Issue by madi** [Open-EO/openeo-qgis-plugin#79]
Hi,

I'm trying to install the plugin from zip but it fails with the following error message:

Couldn't load plugin 'openeo-qgis-plugin-master' due to an error when calling its classFactory() method 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/leomarg/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\openeo-qgis-plugin-master\__init__.py", line 36, in classFactory
    return OpenEO(iface)
  File "C:/Users/leomarg/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\openeo-qgis-plugin-master\openeo_connector.py", line 54, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.3-A Coruña A Coruña, 0e1f846438 

Python Path:
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/leomarg/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/leomarg/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/leomarg/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by niebl** [comment]
Could not replicate the initial QVariant error in zip installation issues. 

The connection error is fixed with the implementation of the openeo python client in 48037ffe64eeebf3ed5d0004b287d6a816cf057d
